### ISSUE TITLE
About the MH sampling in EllDistrSim.R

### ISSUE THREAD

**Issue by bluebirdie** [AlexisDerumigny/ElliptCopulas#3]
Hi, Dr. Derumigny

May I ask a question about the code in your R package ElliptCopulas.
In the line 110 of EllDistrSim.R, the proposal distribution of new Point is not nonegative guaranteed.
And in the line 73 to 77, there is also no constraint put on the sampling to make sure R^2 is nonegative.

How do you make sample of R^2 from MH always nonegative?
Thank you!

**Comment by AlexisDerumigny** [comment]
Hi @bluebirdie 

Thanks for your question! Actually when writing this code, I assumed that the user would give as input a density of R^2 that gives no mass on $]- \infty; 0]$ and therefore would not generate negative values for R^2.
You can see it in the example:
```r
X = EllDistrSim(
  n = 1000, d = 2, mu = c(2,6),
  density_R2 = function(x){return(exp(-x) * (x > 0))} )
```
Because in the function `density_R2` there is a multiplication by `(x > 0)`, this means that the density is always $0$ for negative `x`.

Formally, in line 110 of EllDistrSim.R, the proposal distribution of newPoint is not nonegative guaranteed as you remark, but in line 111 it is written that `newProb = densityFUN(newPoint)` and therefore `newProb = 0`. As a consequence, such a negative value of `newPoint` will make `newProb` equal to $0$ and therefore the proposal will be always rejected in line 113.

Therefore the sample of R^2 from MH is always nonegative (since negative proposals always get rejected as soon as the user-provided density is $0$ for negative values of $x$.
